### ISSUE TITLE
Please, a new simple js script request for Script-for-me

### ISSUE THREAD

**Issue by Decopi** [yobukodori/script-for-me#2]
Hi @yobukodori !

Around six months ago you kindly helped me with a js script, and since then **Script-for-me** works perfectly for me. I tremendously like **Script-for-me** simplicity and minimalism (without loosing its efficiency). It's so lightweight but powerful at the same time. Thank you again and again, and kudos for your work!

Today I'm here once again asking for your help. Just remembering you, I know almost nothing about java script.
And I wonder if it's possible to write a js script for **Script-for-me**, which will block unwanted contents with regular expression matching or wildcards. In simple words, for **Script-for-me**, I need a js script, capable of blocking web content / web traffic defined by regexps or wildcards.

Currently I use [this add-on](https://addons.mozilla.org/en-US/firefox/addon/rule-adblocker/) for that function.
But I want to replace this add-on with **Script-for-me**.
Honestly, I would like to replace all my add-ons with **Script-for-me**. The less add-ons I have, the better!
If **Script-for-me** can manage the blocker js script I need, then my browser performance, privacy and security will improve.

Please, if by chance you can help me writing this sort of blocker js script for **Script-for-me**, then here is the small [list of regexps](https://pastebin.com/uVUj04EQ) and list of [wildcards](https://pastebin.com/uCEAhQGs).

Thank you in advance!

**Comment by yobukodori** [comment]
Script for Me and Rule AdBlocker work on different layers. Therefore, scripts executed by Script for Me cannot replace Rule AdBlocker functions.
